# Generated by Django 3.1.6 on 2021-02-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('task_due_on', models.DateTimeField(verbose_name='Due on')),
                ('task_owner', models.CharField(max_length=200, verbose_name='Owner')),
                ('task_done', models.NullBooleanField(verbose_name='Done')),
            ],
        ),
    ]
