# Generated by Django 3.1.6 on 2021-02-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_done',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_due_on',
            new_name='due_on',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_title',
            new_name='title',
        ),
    ]
